### ISSUE TITLE
Debugging doesn't work

### ISSUE THREAD

**Issue by yay** [aristotelos/cucumber-test-extension#40]
Hi,

I love the extension, but can't get debugging to work. When I hit the debug icon next to a scenario, the vscode switches to the Run and Debug panel, flashes, and I see this printed in Debug Console:

```
(node:55289) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Uncaught Error Error: write EPIPE
    at afterWriteDispatched (<node_internals>/internal/stream_base_commons:159:15)
    at writeGeneric (<node_internals>/internal/stream_base_commons:150:3)
    at Socket._writeGeneric (<node_internals>/net:957:11)
    at Socket._write (<node_internals>/net:969:8)
    at writeOrBuffer (<node_internals>/internal/streams/writable:572:12)
    at _write (<node_internals>/internal/streams/writable:501:10)
    at Writable.write (<node_internals>/internal/streams/writable:510:10)
    at ondata (<node_internals>/internal/streams/readable:1009:22)
    at emit (<node_internals>/events:518:28)
    at addChunk (<node_internals>/internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (<node_internals>/internal/streams/readable:512:3)
    at Readable.push (<node_internals>/internal/streams/readable:392:5)
    at <anonymous> (<node_internals>/internal/worker:343:20)
    at [kOnMessage] (<node_internals>/internal/worker:342:9)
    at <anonymous> (<node_internals>/internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (<node_internals>/internal/event_target:816:20)
    at <anonymous> (<node_internals>/internal/per_context/messageport:23:28)
    at callbackTrampoline (<node_internals>/internal/async_hooks:130:17)
    --- TickObject ---
    at init (<node_internals>/internal/inspector_async_hook:25:19)
    at emitInitNative (<node_internals>/internal/async_hooks:202:43)
    at emitInitScript (<node_internals>/internal/async_hooks:505:3)
    at nextTick (<node_internals>/internal/process/task_queues:143:5)
    at onDestroy (<node_internals>/internal/streams/destroy:116:15)
    at dummyDestroy (<node_internals>/internal/bootstrap/switches/is_main_thread:115:3)
    at _destroy (<node_internals>/internal/streams/destroy:122:10)
    at destroy (<node_internals>/internal/streams/destroy:84:5)
    at Writable.destroy (<node_internals>/internal/streams/writable:1122:11)
    at errorOrDestroy (<node_internals>/internal/streams/destroy:225:12)
    at onwriteError (<node_internals>/internal/streams/writable:612:3)
    at processTicksAndRejections (<node_internals>/internal/process/task_queues:92:21)
    --- TickObject ---
    at init (<node_internals>/internal/inspector_async_hook:25:19)
    at emitInitNative (<node_internals>/internal/async_hooks:202:43)
    at emitInitScript (<node_internals>/internal/async_hooks:505:3)
    at nextTick (<node_internals>/internal/process/task_queues:143:5)
    at onwrite (<node_internals>/internal/streams/writable:647:15)
    at afterWriteDispatched (<node_internals>/internal/stream_base_commons:159:12)
    at writeGeneric (<node_internals>/internal/stream_base_commons:150:3)
    at Socket._writeGeneric (<node_internals>/net:957:11)
    at Socket._write (<node_internals>/net:969:8)
    at writeOrBuffer (<node_internals>/internal/streams/writable:572:12)
    at _write (<node_internals>/internal/streams/writable:501:10)
    at Writable.write (<node_internals>/internal/streams/writable:510:10)
    at ondata (<node_internals>/internal/streams/readable:1009:22)
    at emit (<node_internals>/events:518:28)
    at addChunk (<node_internals>/internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (<node_internals>/internal/streams/readable:512:3)
    at Readable.push (<node_internals>/internal/streams/readable:392:5)
    at <anonymous> (<node_internals>/internal/worker:343:20)
    at [kOnMessage] (<node_internals>/internal/worker:342:9)
    at <anonymous> (<node_internals>/internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (<node_internals>/internal/event_target:816:20)
    at <anonymous> (<node_internals>/internal/per_context/messageport:23:28)
    at callbackTrampoline (<node_internals>/internal/async_hooks:130:17)
    --- MESSAGEPORT ---
    at init (<node_internals>/internal/inspector_async_hook:25:19)
    at emitInitNative (<node_internals>/internal/async_hooks:202:43)
    at Worker (<node_internals>/internal/worker:214:21)
    at InternalWorker (<node_internals>/internal/worker:467:5)
    at HooksProxy (<node_internals>/internal/modules/esm/hooks:506:20)
    at getHooksProxy (<node_internals>/internal/modules/esm/loader:839:18)
    at CustomizedModuleLoader (<node_internals>/internal/modules/esm/loader:731:5)
    at register (<node_internals>/internal/modules/esm/loader:561:30)
    at register (<node_internals>/internal/modules/esm/loader:896:35)
    at getSupportCodeLibrary (/Users/vitaly/projects/graphql-schema-compiler/node_modules/@cucumber/cucumber/lib/api/support.js:28:36)
    at runCucumber (/Users/vitaly/projects/graphql-schema-compiler/node_modules/@cucumber/cucumber/lib/api/run_cucumber.js:49:53)
    --- await ---
    at run (/Users/vitaly/projects/graphql-schema-compiler/node_modules/@cucumber/cucumber/lib/cli/index.js:56:57)
    --- await ---
    at run (/Users/vitaly/projects/graphql-schema-compiler/node_modules/@cucumber/cucumber/lib/cli/run.js:29:28)
    at <anonymous> (/Users/vitaly/projects/graphql-schema-compiler/node_modules/@cucumber/cucumber/bin/cucumber.js:3:37)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1543:14)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1689:10)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1318:32)
    at <anonymous> (<node_internals>/internal/modules/cjs/loader:1128:12)
    at traceSync (<node_internals>/diagnostics_channel:315:14)
    at wrapModuleLoad (<node_internals>/internal/modules/cjs/loader:218:24)
    at executeUserEntryPoint (<node_internals>/internal/modules/run_main:170:5)
    at <anonymous> (<node_internals>/internal/main/run_main_module:36:49)
```

Are there some extra setup steps to make debugging work?

**Comment by aristotelos** [comment]
For me, it works without additional steps. But maybe there are some Cucumber setups that do not work. Could you share your Cucumber-JS version and configuration (cucumber.json)?
